var Afrika08 = 1028;
var Afrika18 = 1235.5;
var SüdAmerika08 = 1132.6;
var SüdAmerika18 = 1261.5;
var Europa08 = 4965.7;
var Europa18 = 4209.3;
var NordAmerika08 = 6600.4;
var NordAmerika18 = 6035.6;
var Asien08 = 12954.7;
var Asien18 = 16274.1;
var Australien08 = 1993;
var Australien18 = 2100.5;
var Total = Afrika18 + SüdAmerika18 + Europa18 + NordAmerika18 + Asien18 + Australien18;
console.log(' ');
console.log('Emissionswerte für Afrika');
console.log('   Die Emission von Afrika ist: ' + Afrika18 + 'kg CO2');
console.log('   Relativ zur Gesamtemission der Welt verursacht Afrika damit ' + (100 / (Total / Afrika18)).toFixed(1) + '%');
console.log('   Für Afrika hat sich 2018 im Vergleich zu 2008 die Emission um ' + (100 / (Afrika18 / Afrika08)).toFixed(1) + '% verändert');
console.log('   2018 im Vergleich zu 2008 sind das ' + (Afrika18 - Afrika08).toFixed(2) + 'kg CO2');
console.log(' ');
console.log(' ');
console.log('Emissionswerte für Süd Amerika');
console.log('   Die Emission von Süd Amerika ist: ' + SüdAmerika18 + 'kg CO2');
console.log('   Relativ zur Gesamtemission der Welt verursacht Süd Amerika damit ' + (100 / (Total / SüdAmerika18)).toFixed(1) + '%');
console.log('   Für Süd Amerika hat sich 2018 im Vergleich zu 2008 die Emission um ' + (100 / (SüdAmerika18 / SüdAmerika08)).toFixed(1) + '% verändert');
console.log('   2018 im Vergleich zu 2008 sind das ' + (SüdAmerika18 - SüdAmerika08).toFixed(2) + 'kg CO2');
console.log(' ');
console.log(' ');
console.log('Emissionswerte für Europa');
console.log('   Die Emission von Europa ist: ' + Europa18 + 'kg CO2');
console.log('   Relativ zur Gesamtemission der Welt verursacht Europa damit ' + (100 / (Total / Europa18)).toFixed(1) + '%');
console.log('   Für Europa hat sich 2018 im Vergleich zu 2008 die Emission um ' + (100 / (Europa18 / Europa08)).toFixed(1) + '% verändert');
console.log('   2018 im Vergleich zu 2008 sind das ' + (Europa18 - Europa08).toFixed(2) + 'kg CO2');
console.log(' ');
console.log(' ');
console.log('Emissionswerte für Nord Amerika');
console.log('   Die Emission von Nord Amerika ist: ' + NordAmerika18 + 'kg CO2');
console.log('   Relativ zur Gesamtemission der Welt verursacht Nord Amerika damit ' + (100 / (Total / NordAmerika18)).toFixed(1) + '%');
console.log('   Für Nord Amerika hat sich 2018 im Vergleich zu 2008 die Emission um ' + (100 / (NordAmerika18 / NordAmerika08)).toFixed(1) + '% verändert');
console.log('   2018 im Vergleich zu 2008 sind das ' + (NordAmerika18 - NordAmerika08).toFixed(2) + 'kg CO2');
console.log(' ');
console.log(' ');
console.log('Emissionswerte für Asien');
console.log('   Die Emission von Asien ist: ' + Asien18 + 'kg CO2');
console.log('    Relativ zur Gesamtemission der Welt verursacht Asien damit ' + (100 / (Total / Asien18)).toFixed(1) + '%');
console.log('   Für Asien hat sich 2018 im Vergleich zu 2008 die Emission um ' + (100 / (Asien18 / Asien08)).toFixed(1) + '% verändert');
console.log('   2018 im Vergleich zu 2008 sind das ' + (Asien18 - Asien08).toFixed(2) + 'kg CO2');
console.log(' ');
console.log(' ');
console.log('Emissionswerte für Australien');
console.log('   Die Emission von Australien ist: ' + Australien18 + 'kg CO2');
console.log('   Relativ zur Gesamtemission der Welt verursacht Australien damit ' + (100 / (Total / Australien18)).toFixed(1) + '%');
console.log('   Für Australien hat sich 2018 im Vergleich zu 2008 die Emission um ' + (100 / (Australien18 / Australien08)).toFixed(1) + '% verändert');
console.log('   2018 im Vergleich zu 2008 sind das ' + (Australien18 - Australien08).toFixed(2) + 'kg CO2');
//# sourceMappingURL=script.js.map